SELECT * from CLASSES;
SELECT * from Students; 
SELECT * from LOGS;
SELECT * from COURSES;
SELECT * from COURSE_CREDIT;
SELECT * from PREREQUISITES;
SELECT * from G_ENROLLMENTS;
SELECT * from SCORE_GRADE;
